builds:
  - goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
    ldflags:
      - -s -w -X main.Version={{.Version}}

archives:
  - replacements:
      darwin: macOS
      linux: Linux
      windows: Windows
      amd64: 64-bit
    format: zip

release:
  draft: true
